spring:
  application:
    name: notification-service
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

    tags:
      application: notification-service
  otlp:
    metrics:
      export:
        resource-attributes:
          service.name: ${spring.application.name}
